### ISSUE TITLE
Version 5.1.1

### ISSUE THREAD

**Issue by rktilia** [BBN-E/bue-common-open#1]
For compiling the code in the following repository, the version 5.1.1 of your tool is needed: [https://github.com/isi-nlp/tac-kbp-eal](https://github.com/isi-nlp/tac-kbp-eal). For this reason, I urgently need this version. Do you maybe have it available and could add it to your repository?

**Comment by gabbard** [comment]
@jayded : you can close this; this was addressed on https://github.com/isi-nlp/tac-kbp-eal/issues/2
